//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.31 at 12:17:07 PM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.w3.org/1999/xhtml")
package org.w3._1999.xhtml;
